name: "rellis"
labels:
  0 : "non-traversable"
  1 : "traversable"
  
color_map: # bgr
  0 : [0, 0, 0]
  1 : [0, 0, 255]

learning_map:
  0 : 0     
  1 : 1      

split: # sequence numbers
  train:
    - 1
    - 2
    - 3
    - 4
  valid:
    - 0
