#batch y todo eso de la red
train:
  voxel_size: 0.2
  batch_size: 8
  max_epochs: 100
  num_workers: 16
  lr: 0.0005
  gamma: 0.1
  weight_decay: 0.05
  max_epochs: 100


test:
  model_path: /home/arvc/Antonio/virtual_environments/trav_analysis/scripts/MinkUtrav/EE/Voxel0.2/BestModel9_th_0.4862739620804787voxel_size0.2_0.9197958031905511.pth
  test_path: /media/arvc/HDD4TB1/Antonio/Minkowski/dataset_recortado_normales_vecinos/valid-refined/0
  output_csv: model/test.csv

